version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.3.2
  node: circleci/node@7.1.0

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: python test_function_app.py

  deploy:
    executor: node/default
    steps:
      - checkout
      - azure-cli/install
      - azure-cli/login-with-service-principal:
          azure-sp: AZURE_CLIENT_ID
          azure-sp-password: AZURE_CLIENT_SECRET
          azure-sp-tenant: AZURE_TENANT_ID
      - run:
          name: Install Azure Functions Tools
          command: npm install -g azure-functions-core-tools@4 --unsafe-perm
      - run:
          name: Publish to Azure Function App
          command: func azure functionapp publish circleciPythonFunctionApp --python

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
